/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    EvalShow: typeof import('./src/components/EvalShow.vue')['default']
    LOGO: typeof import('./src/components/LOGO.vue')['default']
    ResultShow: typeof import('./src/components/ResultShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
